import Header from "@header/header";
import "@style/globals.scss";

import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={raleway.className}>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
